getCourseActivities:
  handler: src/functions/activities/handler.getCourseActivities
  events:
    - httpApi:
        method: GET
        path: /courses/{courseId}/activities

createCourseActivity:
  handler: src/functions/activities/handler.createCourseActivity
  memorySize: 1024
  timeout: 300
  events:
    - httpApi:
        method: POST
        path: /courses/{courseId}/activities

activityPosProcessing:
  handler: src/functions/activities/handler.activityPosProcessing
  events:
    - s3:
        bucket: studdyhub-video-output
        event: s3:ObjectCreated:*
        rules:
          - suffix: .mp4
