service: studdyhub-backend-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverlessUser
  environment:
    NODE_ENV: prod

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - config/.env.dev
  include:
    - config/.env.prod

functions:
  getAllCourses:
    handler: src/handler.getAllCourses
    events:
      - httpApi:
          method: GET
          path: /courses
