service: studdyhub-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverlessUser
  stage: ${opt:stage, 'dev'}
  environment: ${file(./serverless.env.${opt:stage, 'dev'}.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  - ${file(./src/functions/courses/serverless.yml)}
  - ${file(./src/functions/users/serverless.yml)}
  - ${file(./src/functions/activities/serverless.yml)}
  - ${file(./src/functions/enrollments/serverless.yml)}
