service: studdyhub-serverless

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: serverlessUser
  stage: ${opt:stage, 'dev'}
  environment: ${file(./serverless.env.${opt:stage, 'dev'}.yml)}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:*Bucket
        - s3:*Object
      Resource:
        - "arn:aws:s3:::video-uploads00925-production/*"
        - "arn:aws:s3:::video-uploads212329-dev/*"
        - "arn:aws:s3:::studdyhub-video-input/*"
        - "arn:aws:s3:::studdyhub-video-output/*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:CreateTable
        - dynamodb:UpdateTable
        - dynamodb:UpdateTimeToLive
        - dynamodb:DescribeTimeToLive
        - dynamodb:ListTagsOfResource
        - dynamodb:TagResource
        - dynamodb:UntagResource
      Resource: "*"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  - ${file(./src/functions/courses/serverless.yml)}
  - ${file(./src/functions/users/serverless.yml)}
  - ${file(./src/functions/activities/serverless.yml)}
  - ${file(./src/functions/enrollments/serverless.yml)}
  - ${file(./src/functions/database/serverless.yml)}
