getAllCourses:
  handler: src/functions/courses/handler.getAllCourses
  events:
    - httpApi:
        method: GET
        path: /courses

getCourseById:
  handler: src/functions/courses/handler.getCourseById
  events:
    - httpApi:
        method: GET
        path: /courses/{id}

getCoursesByUserId:
  handler: src/functions/courses/handler.getCoursesByUserId
  events:
    - httpApi:
        method: GET
        path: /courses/user/{id}

createCourse:
  handler: src/functions/courses/handler.createCourse
  events:
    - httpApi:
        method: POST
        path: /courses

updateCourse:
  handler: src/functions/courses/handler.updateCourse
  events:
    - httpApi:
        method: PATCH
        path: /courses/{id}

deleteCourse:
  handler: src/functions/courses/handler.deleteCourse
  events:
    - httpApi:
        method: DELETE
        path: /courses/{id}
