createUser:
  handler: src/functions/users/handler.createUser
  events:
    - httpApi:
        method: POST
        path: /users

getUserByCognitoId:
  handler: src/functions/users/handler.getUserByCognitoId
  events:
    - httpApi:
        method: GET
        path: /users/{id}

updateUser:
  handler: src/functions/users/handler.updateUser
  events:
    - httpApi:
        method: PATCH
        path: /users/{id}

deleteUser:
  handler: src/functions/users/handler.deleteUser
  events:
    - httpApi:
        method: DELETE
        path: /users/{id}
