createUser:
  handler: src/functions/users/handler.createUser
  events:
    - httpApi:
        method: POST
        path: /users

getUserByCognitoId:
  handler: src/functions/users/handler.getUserByCognitoId
  events:
    - httpApi:
        method: GET
        path: /users/{id}
